services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./app/index.html:/usr/share/nginx/html/index.html
      - ./config/version.txt:/usr/share/nginx/html/version.txt